project_name: "Predictive_Maintenance_v1"
author: "Akshay Kumar G"

data:
  raw_path: "data/raw/ai4i2020.csv"
  processed_dir: "data/processed/"
  current_version: "v1"
  production_dir: "data/production/"
  target_column: "Machine failure"


preprocessing:
  test_size: 0.3
  random_state: 42
  scale_numeric: true
  encode_categorical: true

model:
  algorithm: "LogisticRegression"
  n_estimators_RF: 100
  max_depth_RF: 10
  random_state_RF: 42
  lr_C: 0.1

registry:
  model_dir: "models/"
  current_model_version: "model_v2"

deployment:
  model_path: "models/model_v1.pkl"
  port: 5000
  threshold: 0.75



